### ISSUE TITLE
Excalidraw Room (Collaboration Server)

### ISSUE THREAD

**Issue by bojanraic** [onedr0p/containers#1017]
### Application Name

Excalidraw Room

### Application Source Code URL

https://github.com/excalidraw/excalidraw-room

### Application Language

Typescript

### Application Architectures

linux/arm64, linux/amd64

### Additional Information

Excalidraw has a feature to start a live collab session and do collaborative drawing. This requires excalidraw-room, or the collaboration server to be configured. The excalidraw deployment then needs to point to this server in order to enable live drawing/collab session. 

### Assign to self

- [ ] I will create a PR to containerize this application myself

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by onedr0p** [comment]
Sorry I am not interested in supporting this.
