### ISSUE TITLE
HASS: `libcap` not available

### ISSUE THREAD

**Issue by samip5** [onedr0p/containers#1026]
```
2024-05-17 14:59:06.501 ERROR (SyncWorker_1) [aiodhcpwatcher] Cannot watch for dhcp packets without a functional packet filter: libpcap is not available. Cannot compile filter
```

Version: 2024.5.3

**Comment by onedr0p** [comment]
I think this is expected because you can't have the functionality without running the container as root.

**Comment by samip5** [comment]
> I think this is expected because you can't have that functionality without running the container as root.

I think that sounds more like the library not being available instead of it not being able to be used.

**Comment by onedr0p** [comment]
Maybe? I see the error on my end too but I don't lose any functionality.

**Comment by samip5** [comment]
Yeah, I'm gonna just close this as it does seem to be mostly a warning only.
