### ISSUE TITLE
Update lidarr-plugins

### ISSUE THREAD

**Issue by cedvan** [onedr0p/containers#1042]
Hi,

I found this history change : 
https://github.com/onedr0p/containers/commit/da7a27a99eabcdd4c664d8af5249e5fce975dcea

Can you rollback this change and update lidarr-plugins version please ?

**Comment by onedr0p** [comment]
This build was always failing for one reason or another, and since I don't even use lidarr I found it a nuance to maintain.

Feel free to use @crutonjohn container here https://github.com/crutonjohn/personal-containers

**Comment by cedvan** [comment]
Ok 😢 , I can't use another container, my home server is powered by Truenas/Truecharts

**Comment by crutonjohn** [comment]
> Ok 😢 , I can't use another container, my home server is powered by Truenas/Truecharts

do they not provide the ability to override image/tag?

**Comment by crutonjohn** [comment]
> > Ok 😢 , I can't use another container, my home server is powered by Truenas/Truecharts
> 
> do they not provide the ability to override image/tag?

tbh I probably need to file an upstream issue with the plugins stakeholders. I haven't been able to get the plugin to work for a bit now, just been working around it.

**Comment by onedr0p** [comment]
Truenas SCALE is dropping k3s support anyways. Probably good to look at alternatives, they are going to be supporting docker/docker-compose moving forward.

https://forums.truenas.com/t/the-future-of-electric-eel-and-apps/5409

**Comment by cedvan** [comment]
@crutonjohn Not ability, but I can create an custom app, I try this solution actually. 

> tbh I probably need to file an upstream issue with the plugins stakeholders. I haven't been able to get the plugin to work for a bit now, just been working around it.
So your container plugins not work ?

@onedr0p 
Yes, I will switch to talos linux. But this change is very important...

**Comment by cedvan** [comment]
Hum, some endpoints in Deemix are break with last Deezer changes.
So add deemix indexer not works and trigger a deemix crash.

cf. https://github.com/youegraillot/lidarr-on-steroids/pull/65
cf. https://gitlab.com/Bockiii/deemix-docker/-/issues/146

I'm tired, lidarr have always new problem. I'll remove lidarr and only use deemix web ui + plex
