### ISSUE TITLE
Tautulli 2.14.2 released but latest available is 2.13.4

### ISSUE THREAD

**Issue by drtaru** [onedr0p/containers#1052]
Tautulli had a new stable release 3 weeks ago. 
Requesting a container update.
https://github.com/Tautulli/Tautulli/releases/tag/v2.14.2

**Comment by onedr0p** [comment]
I no longer build Tautulli https://github.com/onedr0p/containers/pull/1006

I'm using the official image and overriding the entrypoint to avoid gosu.
