### ISSUE TITLE
qBittorrent .fastresume files can't be overwritten and/or rewritten?

### ISSUE THREAD

**Issue by mrand01** [onedr0p/containers#1064]
Having a very odd problem with this container.  I'm running it via TrueNAS Scale, so there's an additional layer of overhead that I'm aware of.

The app will not rewrite .fastresume files.  If one already exists for a given torrent, I get the following error message: ```"Couldn't save torrent resume data to '/config/qBittorrent/BT_Backup/[INSERT_HASH_HERE].fastresume'. Error: Operation not permitted."```

If I go and manually delete the .fastresume files, then pause all torrents, then resume all torrents, qBittorrent regenerates the .fastresume files. But only once. The next time it tries to update the .fastresume files I'm met with the same error message in the execution log.

What would cause this app to be able to write a specific file, but not overwrite/append the same file?  It seems to be a permissions issue, but I've never encountered a problem quite like this one.

**Comment by onedr0p** [comment]
You definitely have an issue with file permissions, many people use this container including me without issues outside of SCALE. Unfortunately I don't support the SCALE platform and never planned or wanted to. I would take this up with their community.
