### ISSUE TITLE
Expose HTTPS Port options to SABnzbd enviroment variables 

### ISSUE THREAD

**Issue by bitrage** [onedr0p/containers#1070]
Relevant for https://github.com/truenas/charts/issues/2693

For easy setup in TrueNAS it would be advantageous to have the option for "HTTPS Port" inside the SABnzbd advanced config. Could you please expose this option as an additional enviroment variable?

The option sets the following sabnzbd.ini attributes:

[misc]
https_port = 30060

You could couple it with an additional enviroment variable for enable_https = 1.

Thank you!

**Comment by onedr0p** [comment]
I'm not sure why you would want to terminate TLS at sabnzbd instead of an ingress controller, can you explain your need for this option? I don't support truenas scale or truecharts so it's very unlikely this will be added.
