### ISSUE TITLE
Helm chart for onedr0p images built with secure deployments in mind

### ISSUE THREAD

**Issue by bernardgut** [onedr0p/containers#1096]
### Application Name

Sonarr,Radarr,Lidarr,Prowlarr,Plex,Transmission

### Application Source Code URL

https://github.com/sekops-ch/k8s-mediamanager

### Application Language

Other

### Application Architectures

linux/arm64

### Additional Information

If anyone is interested, You can find it here https://github.com/sekops-ch/k8s-mediamanager. I intend to fully support it.

Cheers.
B.

### Assign to self

- [x] I will create a PR to containerize this application myself

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by onedr0p** [comment]
Nice work! I think most of us using k8s are using these images with the app-template from https://github.com/bjw-s/helm-charts
