### ISSUE TITLE
Bazarr timezone hard coded to UTC as Env variable

### ISSUE THREAD

**Issue by Jon87** [onedr0p/containers#1098]
I think the timezone is hardcoded as UTC somewhere, can't seem to override it and it's adjusting the clock to be incorrect for my time zone.

When I tried to use an additional environment variable to change I got the error;

"Error: UPGRADE FAILED: execution error at (bazarr/templates/common.yaml:11:4): Container - Environment Variable [TZ] in [envList] tried to override the Environment Variable that is already defined in [fixedEnv]"

Thanks for looking!

**Comment by onedr0p** [comment]
Are you sure you are not defining TZ twice in your deployment? It's UTC by default as set in the Dockerfile but it can be overridden as I'm doing here...

https://github.com/onedr0p/home-ops/blob/a61d931e673e5075c8f74dab33e3972490af1ca5/kubernetes/main/apps/default/bazarr/app/helmrelease.yaml#L41
