### ISSUE TITLE
lidarr-develop: stuck on v2.5.2.4316 | lidarr: stuck on v2.4.3.4248

### ISSUE THREAD

**Issue by v3DJG6GL** [onedr0p/containers#1103]
The lidarr containers don't seem to have been updated for several weeks:

- [lidarr-develop](https://github.com/onedr0p/containers/pkgs/container/lidarr-develop) is still on v2.5.2.4316. The latest pre-release version is [v2.6.2.4379](https://github.com/Lidarr/Lidarr/releases/tag/v2.6.2.4379)
- [lidarr](https://github.com/onedr0p/containers/pkgs/container/lidarr) is still on v2.4.3.4248. The latest official version is [v2.5.3.4341](https://github.com/Lidarr/Lidarr/releases/tag/v2.5.3.4341)

**Comment by onedr0p** [comment]
https://github.com/onedr0p/containers/pull/1087

**Comment by v3DJG6GL** [comment]
Oh, thanks for the hint!
Any chance you might reconsider your decision? I know a few people who use this Lidarr container, and the app - as well as the metadata functions - work flawlessly for all of us...

**Comment by onedr0p** [comment]
This repo is more about containers I personally use and support. Unfortunately readarr and lidarr have some serious flaws for me to pick them back up again.  I get they probably work fine for you and others. Maybe in the future after more development time I might see myself using them again but both of these feel very alpha to me and many others who used to run them.

The great thing about this repo is that is can be forked and be used to build your own containers which [a lot of people have been doing](https://github.com/onedr0p/containers/forks).
