### ISSUE TITLE
Sabnzbd: Can't accept incoming IPv6 traffic

### ISSUE THREAD

**Issue by 9numbernine9** [onedr0p/containers#1110]
Greetings!

I'm deploying some of your containers in an IPv6-only Kubernetes cluster and I'm running into some difficulty with Sabnzbd. Specifically, it seems the way things are set up it can't listen on IPv6, even if configured in the UI and/or `sabnzbd.ini` to do so after initially launching it. I _think_ the issue is that the `entrypoint.sh` script is explicitly configured to [listen on `0.0.0.0`](https://github.com/onedr0p/containers/blob/main/apps/sabnzbd/entrypoint.sh#L24). I believe that because this is configured on the command line it effectively overrides anything that's put into the `sabnzd.ini` configuration file. 

According to [the docs](https://sabnzbd.org/wiki/configuration/4.3/general) it should be possible to set the listening address to `::` and then it would listen on both IPv4 _and_ IPv6, which I feel is reasonable. If that seems like a concern to you, however, it would be nice if there were a `SABNZBD__ADDRESS` environment variable (similar to `SABNZBD__PORT`) that could be used to configure this value at deployment time instead and the default value of `SABNZBD__ADDRESS` could be `0.0.0.0`.

Thanks for taking the time to read this and maintaining these great containers!

**Comment by onedr0p** [comment]
I'd be down review a PR as long as the default is set to 0.0.0.0

**Comment by onedr0p** [comment]
Not certain how much this was going to help, I see this arg on sabnzbd.py

```
--ipv6_hosting <0|1>    Listen on IPv6 address [::1] [*]
```

**Comment by 9numbernine9** [comment]
I _think_ it will work without setting that. The wiki says:

> Some systems have problems dealing with the IPv6 equivalent of "localhost" for SABnzbd host. Therefore SABnzbd will not try to bind to the IPv6 localhost by default when the SABnzbd host is set to "localhost". Enabling this will binding to all addresses of localhost. Alternatively you can also set the SABnzbd host to ::1 to only bind to the IPv6 localhost.

... So I think you only might need that setting if you explicitly choose `localhost` as the server address. Since our default is `0.0.0.0` and we're trying to make it work with `::`, I think it should be OK. I'll definitely give it a try the next time the container is built!

**Comment by 9numbernine9** [comment]
Update: Pulled the latest `4.3.3` digest and everything works perfectly when I set `SABNZBD__ADDRESS` to `::`. 🚀 

Thanks!
