### ISSUE TITLE
Plex (Media Server) Outdated

### ISSUE THREAD

**Issue by bitpushr** [onedr0p/containers#120]
Hi,

I'm a user of the TrueCharts project, and they use your Plex container as their upstream source.

https://github.com/truecharts/containers/commit/bb4574b03ae00be88a73e4ad7b36b42d6d5175b9

 I just noticed that PMS 1.30.0.6486 was made available 9 days ago now, and your container hasn't yet updated to it. Just wondering if you're planning to update it to the latest version?

Thanks!

**Comment by onedr0p** [comment]
This is already published...

https://github.com/onedr0p/containers/pkgs/container/plex
