### ISSUE TITLE
Requesting container for haste-server

### ISSUE THREAD

**Issue by samip5** [onedr0p/containers#141]
### Application Name

haste-server

### Application Source Code URL

https://github.com/toptal/haste-server

### Application Language

Other

### Application Architectures

linux/arm64, linux/amd64

### Additional Information

Upstream doesn't seem to publish images.

### Assign to self

- [X] I will create a PR to containerize this application myself

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by onedr0p** [comment]
Sorry, but I'd rather not. There are other pastebin alternatives out there better than this.

Fuck toptal https://github.com/toptal/haste-server/issues/396

**Comment by samip5** [comment]
Oh, shit. That's just a shit show of an issue. Yeah let's not.
