### ISSUE TITLE
Add Kopia UI in the Kopia image?

### ISSUE THREAD

**Issue by FlorentLM** [onedr0p/containers#154]
### Application Name

Kopia UI

### Application Source Code URL

https://github.com/kopia/kopia

### Application Language

Go

### Application Architectures

linux/arm64, linux/amd64

### Additional Information

Title says pretty much all - Would.be nice to have the Kopia image to also grap the kopia-ui tar.gzip and the ability to enable the UI via an env variable 

### Assign to self

- [ ] I will create a PR to containerize this application myself

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by onedr0p** [comment]
I think this is already possible? That kopia binary include should contain both.

**Comment by FlorentLM** [comment]
Indeed, it's in there. My bad!
