### ISSUE TITLE
bazarr postgres support

### ISSUE THREAD

**Issue by xstar97** [onedr0p/containers#159]
is there anyway for you to add this section via custom variables like you had done for the other arr apps?

https://wiki.bazarr.media/Additional-Configuration/PostgreSQL-Database/#database-creation
```
[postgresql]
enabled = True
host = localhost
port = 5432
database = bazarr
username = _<postgres_username>_
password = _<postgres_password>_
```

**Comment by xstar97** [comment]
> Maybe this could be done, I've tried to reach out to the developers of bazarr and asked them to allow these to be set via env but they do not care. I'll accept any PRs if anyone wants to try and implement this but I don't have time to right now.

ok mate, thx for the info. ill take a look at it later then.

**Comment by onedr0p** [comment]
If taking a look into adding support keep in mind that the config file is written to from the UI, and that we cannot template out that file to do an envsubst on. Which means in this case we will need to parse the ini file and inject the ENV values into the ini file on start. If you have any idea on any tools that can be used for manipulating INI files I am all ears.

```ini
[postgresql]
enabled = False
host = localhost
port = 5432
database =
username =
password =
```

**Comment by xstar97** [comment]
some ideas from chatGPT.

```shell
#!/bin/bash

# Function to read an INI file and return a dictionary of its sections and values
read_ini_file () {
    sections=()
    while read line; do
        if [[ $line =~ ^\[.*\]$ ]]; then
            current_section="${line:1:-1}"
            sections["$current_section"]=""
        elif [[ $line =~ ^[^#]*=.* ]]; then
            key="${line%%=*}"
            value="${line#*=}"
            sections["$current_section"]+="$key=$value"$'\n'
        fi
    done < "$1"
    for section in "${!sections[@]}"; do
        section_values="${sections[$section]}"
        section_values="${section_values%$'\n'}"
        sections["$section"]="$(echo -e "$section_values")"
    done
    echo "${sections[@]}"
}

# Function to write a dictionary of sections and values to an INI file
write_ini_file () {
    for section in "${!1[@]}"; do
        section_values="${1[$section]}"
        echo "[$section]" >> "$2"
        echo -e "$section_values" | sed 's/^/  /' >> "$2"
    done
}

# Example usage:
ini_file_path="example.ini"

# Read the INI file
read_ini_file "$ini_file_path"

# Print the contents of the INI file
echo "${sections[@]}"

# Manipulate the contents of the INI file
sections["Section1"]="${sections[Section1]/key1=new value/key1=modified value}"
sections["Section2"]+="key3=new value"$'\n'

# Write the modified INI file
write_ini_file sections "$ini_file_path"
```

**Comment by onedr0p** [comment]
Closing this issue, looks like the next release will have this feature hopefully.

**Comment by GeorgeGedox** [comment]
Just tried on version 1.2.3 and it doesn't seem to work, I can see the env vars in the pod but the config.ini file is still using defaults

**Comment by onedr0p** [comment]
Works for me, maybe debug more and then open an issue on bazarr GitHub instead of here?
