### ISSUE TITLE
Add Autoscan (with postgres) container

### ISSUE THREAD

**Issue by aleksasiriski** [onedr0p/containers#164]
### Application Name

Autoscan

### Application Source Code URL

https://github.com/aleksasiriski/autoscan

### Application Language

Go

### Application Architectures

linux/arm64, linux/amd64

### Additional Information

I'm working on moving from S6 overlay to a solution based on these containers and would love for it to be hosted here, since I'll be using the alpine image as a base anyway.

### Assign to self

- [X] I will create a PR to containerize this application myself

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by onedr0p** [comment]
Sounds good to me!
