### ISSUE TITLE
[DISCUSSION] Distroless

### ISSUE THREAD

**Issue by aleksasiriski** [onedr0p/containers#168]
*Enable discussions so this doesn't have to be under issues*

What's your opinion on distroless? I was thinking about making my own set of images similar to yours but based on [google's](https://github.com/GoogleContainerTools/distroless) debian implementation?

Also, I can understand Alpine as a base (even though musl sometimes has issues) but why did you choose Ubuntu over Debian?

**Comment by onedr0p** [comment]
I think distroless containers are great for applications that don't have any OS dependency, like a statically compiled Go binary. A lot of the containers built here don't really fall under that criteria.

Ubuntu was chosen due to having more up-to-date packages for certain things in their repos.

**Comment by onedr0p** [comment]
Unfortunately swapping base images to something other than Ubuntu or Alpine is quite a bit of effort and lots of testing to do. These two were chosen to keep things simple with the least amount of friction.

As these images are mostly geared towards homelab usage the security posture can be a little a bit relaxed. I'm not saying it's perfect but engineering for security creates more work, more hassle. I leave those problems to be solved in a business and not really a hobbyist project if they aren't very critical CVEs.
