### ISSUE TITLE
LinkStack

### ISSUE THREAD

**Issue by samip5** [onedr0p/containers#176]
### Application Name

LinkStack

### Application Source Code URL

https://github.com/LinkStackOrg/LinkStack

### Application Language

PHP

### Application Architectures

linux/arm64, linux/amd64

### Additional Information

They don't seem to be doing a good job with creating the container upstream..

It's privileged, eg running as root...

Upstream container sources: https://github.com/LinkStackOrg/linkstack-docker (if one mounts htdocs to a pvc, it just doesn't have any content anymore..)

### Assign to self

- [ ] I will create a PR to containerize this application myself

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by onedr0p** [comment]
> They don't seem to be doing a good job with creating the container upstream..

Well it is PHP 😬

**Comment by samip5** [comment]
It also uses sqlite by default, but can be configured to use MySQL as well. :thinking:

**Comment by onedr0p** [comment]
No postgres support? :(

**Comment by samip5** [comment]
Doesn't seem like so. :(

**Comment by onedr0p** [comment]
Someone should just take the UI and put it behind a Go/Rust app. I really try avoid PHP at all costs unless the developers have a clue about roadrunner or openswoole.
