### ISSUE TITLE
unpackerr: Included tini executeable in arm64 image is not arm64 compatible

### ISSUE THREAD

**Issue by samip5** [onedr0p/containers#178]
ghcr.io/onedr0p/unpackerr:0.11.2@sha256:9781814f461b08b44be372b50f7797e951f6d832e5f98e795ba364136eb688ad seems to have incorrect tini for arm64.

```
$ k logs -n media unpackerr-5c76bc9d8d-9ww74
exec /sbin/tini: exec format error
```

**Comment by onedr0p** [comment]
Does the same thing happen when you don't pin the digest?
