### ISSUE TITLE
Porla

### ISSUE THREAD

**Issue by samip5** [onedr0p/containers#183]
### Application Name

Porla

### Application Source Code URL

https://github.com/porla/porla

### Application Language

Other

### Application Architectures

linux/arm64, linux/amd64

### Additional Information

It seems to be C++ app and it also seems to be using alpine as base by default.

### Assign to self

- [ ] I will create a PR to containerize this application myself

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by onedr0p** [comment]
Looks like they are working on a container?
https://github.com/porla/porla/pkgs/container/porla

**Comment by samip5** [comment]
They have a container yes, but it doesn't seem very k8s friendly as https://github.com/samip5/k8s-cluster/blob/main/cluster/apps/downloads/porla/app/helm-release.yaml results in sqlite errors, possibly due to the runAsUser things. :/

**Comment by onedr0p** [comment]
The dockerfile looks fine from here.

https://github.com/porla/porla/blob/main/Dockerfile#L25-L33

**Comment by samip5** [comment]
Don't know what to tell ya.

```
[2023-06-03 15:43:51.342336] [0x00007f4de686ea60] [fatal]   Failed to open SQLite connection: unable to open database file
[2023-06-03 15:43:51.369412] [0x00007f4de686ea60] [error]   Failed to vacuum database: unable to open database file
[2023-06-03 15:43:51.369446] [0x00007f4de686ea60] [fatal]   Failed to load configuration
```

**Comment by onedr0p** [comment]
Maybe try setting the env

PORLA_DB: /config/porla.sqlite

and use /config

**Comment by samip5** [comment]
I did set `mountPath: /var/lib/porla` on the config but... It's more than likely just user error. :)
