### ISSUE TITLE
Applications are not built after pull request is merged

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/containers#22]
I just merged rtorrent and flood in https://github.com/onedr0p/containers/pull/21 and noticed (as expected) that no pipeline was kicked off. It isn't a huge problem as the container will be built on the next release schedule cycle. Not sure if we should bother with an implementation to fix this?

**Comment by onedr0p** [comment]
After thinking this over I think this is okay. The schedule runs every hour and maintainers can kick off a manual build after a PR is merge if we're impatient.

**Comment by bjw-s** [comment]
Agreed... doesn't add that much value when the release flow runs every hour anyway.

**Comment by bjw-s** [comment]
Well, implemented it anyway because some images were not being rebuilt when the base image changed 😄
