### ISSUE TITLE
Requesting Smokeping container

### ISSUE THREAD

**Issue by samip5** [onedr0p/containers#324]
### Application Name

Smokeping

### Application Source Code URL

https://oss.oetiker.ch/smokeping/index.en.html

### Application Language

Other

### Application Architectures

linux/arm64, linux/amd64

### Additional Information

It's written in Perl, but it's widely used. I couldn't find any non-root containers though. :(

### Assign to self

- [ ] I will create a PR to containerize this application myself

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by onedr0p** [comment]
I don't really have much interest in adding this sorry, maybe there's a image out there you can use instead?
