### ISSUE TITLE
Fix Radarr build

### ISSUE THREAD

**Issue by fastlorenzo** [onedr0p/containers#590]
Hi mate, I managed to fix the Radarr nightly build (cf. https://github.com/fastlorenzo/containers/pull/73/commits/477da956935c4c2589162b67e07734ee5c93c7a9)

Thought it might be useful to you give it fails in your actions as well.

This is due to the following change in Radarr code: https://github.com/Radarr/Radarr/pull/9000

**Comment by onedr0p** [comment]
I removed the nightly build but I'm down for adding it back, thanks for the tip!

**Comment by onedr0p** [comment]
Radarr nightly is being built again.
