### ISSUE TITLE
Transmission web ui 404's

### ISSUE THREAD

**Issue by mynamewastaken** [onedr0p/containers#77]
Unsure at what point this broke for me, but sometime between migrating between the former `k8s-at-home` images and these, the web ui in transmission broken.

It 404'd out with `web/index.html` couldn't be found. I noticed that the `TRANSMISSION_WEB_HOME=/app/web` env var was not properly being set. I don't know what the fix is, but explicitly setting it in the (k8s-at-home/transmission) helm chart's values.yaml worked for me. 

Posting in case anyone else ran into this.

**Comment by onedr0p** [comment]
The default UI is pretty shitty but that's just overall my opinion on transmission 😉

I tested adding a different web ui using the following config

https://github.com/onedr0p/home-ops/tree/ae13ac33b07d6fed346e5a57018289e1e965d1dd/archive/apps/transmission

**Comment by onedr0p** [comment]
But for the default UI the env it's set

https://github.com/onedr0p/containers/blob/aef4b6ed8b5a304e405935e59a5d4a313235ee42/apps/transmission/Dockerfile#L12

**Comment by ishioni** [comment]
> But for the default UI the env it's set
> 
> https://github.com/onedr0p/containers/blob/aef4b6ed8b5a304e405935e59a5d4a313235ee42/apps/transmission/Dockerfile#L12

And yet when running
```
bash-5.1$ printenv | grep WEB
WEBUI_PORT=9091
TRANSMISSION_WEB_HOME=/web
```

Didn't have time to investigate why this happens yet
