### ISSUE TITLE
Add bitwarden-cli container for External Secrets integration

### ISSUE THREAD

**Issue by dkw99** [onedr0p/containers#874]
### Application Name

bitwarden-cli

### Application Source Code URL

https://github.com/bitwarden/clients

### Application Language

Typescript

### Application Architectures

linux/amd64

### Additional Information

Add container to support bitwarden-cli integration based on example at https://external-secrets.io/v0.9.5/examples/bitwarden/#requirements, using alpine instead of debian sid.

### Assign to self

- [X] I will create a PR to containerize this application myself

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by onedr0p** [comment]
I don't really have much interest in adding this, maybe there's a image out there you can use instead?
