### ISSUE TITLE
Add support for Intel 12 Gen+ in Jellyfin

### ISSUE THREAD

**Issue by aumer-amr** [onedr0p/containers#898]
### Application Name

Jellyfin

### Application Source Code URL

https://github.com/jellyfin/jellyfin

### Application Language

.Net

### Application Architectures

linux/arm64, linux/amd64

### Additional Information

As per https://jellyfin.org/docs/general/administration/hardware-selection Intel Graphics 12 Gen+ require a linux kernel of 6.2+ and the jellyfin container runs 6.1

`Linux jellyfin-0 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 x86_64 x86_64 GNU/Linux`

They also mention that it's recommended to use jellyfin-ffmpeg6 instead of 5 as per `It is also recommended that jellyfin-ffmpeg6 be installed instead of the default jellyfin-ffmpeg5 on these hardware platforms.`

I could shoot in a PR for jellyfin-ffmpeg6 but I don't really know the best approach to combine this with the kernel update.

### Assign to self

- [ ] I will create a PR to containerize this application myself

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by onedr0p** [comment]
Containers use the host OS kernel.

**Comment by onedr0p** [comment]
I have update the dockerfile to use jellyfin-ffmpeg6

https://github.com/onedr0p/containers/commit/ab2684e11f2f22bd1ed25684a03b90970996abed

**Comment by aumer-amr** [comment]
Ah shit, thank you! Will wait for debian to update then.
