### ISSUE TITLE
Fix Lidarr build

### ISSUE THREAD

**Issue by fastlorenzo** [onedr0p/containers#900]
Same as for #590, the template config file of Lidarr needs to be fixed (cf https://github.com/fastlorenzo/containers/commit/f731c834b8d5ffa895b101e67d682c16361d9f56 for the fix)

https://github.com/onedr0p/containers/blob/da1ce75a41aaadf94ebe4c1e5b155a0b1ae79393/apps/lidarr/config.xml.tmpl#L7

**Comment by onedr0p** [comment]
Thanks, I have updated it in https://github.com/onedr0p/containers/commit/92cf013820755d3e1ea15929dca3dfed693f0063 I know the stable release will fail but eventually it will start working when they push a new stable version.
