### ISSUE TITLE
Reduce commit spam by moving container information elsewhere

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/containers#941]
While I love the idea of having these containers and badges it does come at an expense of having a lot of spam in the commit log. Ideally it would be great to move these to outside the README maybe in the Github wiki?

**Comment by onedr0p** [comment]
https://github.com/marketplace/actions/github-wiki-action

**Comment by rtrox** [comment]
Yea... this is getting sort of spammy, especially with all the minor version changes. contributor doesn't give me access to set up wiki pages, but if you want to get a skeleton wiki set up, I should be able to work on the automation to write there. It looks like the wiki is just a hidden git repo, so it shouldn't be too crazy to get it moved over:

https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages#adding-or-editing-wiki-pages-locally

**Comment by onedr0p** [comment]
@rtrox I wonder if it's better to just remove it, while not ideal people can visit the [packages](https://github.com/onedr0p?tab=packages&repo_name=containers) section to see images and tags.

The wiki idea isn't great because it's also moving it out of sight like the packages section should be. I think this can be revisited when [shields.io supports GHCR](https://github.com/badges/shields/issues/5594)?
