### ISSUE TITLE
Add transmission-remote to Transmission container

### ISSUE THREAD

**Issue by amasover** [onedr0p/containers#943]
It would be nice to have transmission-remote baked in, in addition to transmission-cli.

https://pkgs.alpinelinux.org/package/edge/community/x86_64/transmission-remote

**Comment by onedr0p** [comment]
Done in https://github.com/onedr0p/containers/commit/3447221134d6bef3cfbdbffc14c596a42a296fbf

**Comment by onedr0p** [comment]
Should be ready after this builds

https://github.com/onedr0p/containers/actions/runs/7435013121
