### ISSUE TITLE
Plex-Image-Cleanup

### ISSUE THREAD

**Issue by airbornetrooper82573** [onedr0p/containers#955]
### Application Name

Plex-Image-Cleanup

### Application Source Code URL

https://github.com/meisnate12/Plex-Image-Cleanup

### Application Language

Python

### Application Architectures

linux/arm64

### Additional Information

This a script that complements plex-meta-manager and helps cleanup image data.

### Assign to self

- [ ] I will create a PR to containerize this application myself

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by onedr0p** [comment]
It looks like the upstream image doesn't use s6-overlay. Maybe PR GHCR support to their repo if you want a different registry outside dockerhub?
