### ISSUE TITLE
Home-Assistant 2024.2.2 complains about Python 3.11.6

### ISSUE THREAD

**Issue by kevinastone** [onedr0p/containers#963]
Running the `2024.2.2` home-assistant container you build gives the following warning:
```
Support for running Home Assistant in the current used Python version 3.11.6 is deprecated and will be removed in Home Assistant 2024.4. Please upgrade Python to 3.12 to prevent your Home Assistant instance from breaking.
```

It looks like you build on top of an alpine base container of your own: https://github.com/onedr0p/containers/pkgs/container/alpine.  It doesn't look like alpine has python3 `3.12` in their `3.19` release.

**Comment by onedr0p** [comment]
I saw that too and hoping that Alpine 3.20 will make it out before HASS does, I'll keep this issue open as it should be addressed before April.

**Comment by onedr0p** [comment]
It is also worth noting that Alpine Edge doesn't eve have 3.12, so this might be an issue if come April Alpine doesn't package 3.12

https://pkgs.alpinelinux.org/packages?name=python3&branch=edge&repo=&arch=&maintainer=

**Comment by rtrox** [comment]
One option would be to add a  base image based on [`python:3.12-alpine`](https://hub.docker.com/_/python), the python maintainers just [build python from source](https://github.com/docker-library/python/blob/eba24df439d48988302a60cf9ef5cddd5d49b51f/3.12/alpine3.19/Dockerfile#L59-L101) in their base image.

**Comment by onedr0p** [comment]
Good point, we'll see what things are like in a month.

**Comment by onedr0p** [comment]
I went with @rtrox suggestion for now until Alpine supports 3.12 in their pkg repos.

https://github.com/onedr0p/containers/issues/978
