### ISSUE TITLE
Fix libturbojpeg

### ISSUE THREAD

**Issue by evanrich** [onedr0p/containers#988]
### Application Name

home assisstant

### Application Source Code URL

NA

### Application Language

.Net

### Application Architectures

linux/amd64

### Additional Information

there seems to be an issue with libturbojpeg.  I opened a bug on https://github.com/home-assistant/core/issues/114997  but realized I was using your image. 

### Assign to self

- [X] I will create a PR to containerize this application myself

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by onedr0p** [comment]
I'm not sure what the fix is here? I'm already using the new package for Alpine 3.19

https://github.com/onedr0p/containers/blob/main/apps/home-assistant/Dockerfile#L63

**Comment by onedr0p** [comment]
No response and not sure what to do here.
